name: testGit
on: push
jobs:
  myTest:
    runs-on: ubuntu-latest
    env:
      DB_HOST: localhost
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      DB_CONNECTION: pgsql
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: 3155810a
          DB_CONNECTION: pgsql
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
      - name: Instal
        run : make install
      - name: Run linter
        run : make lint
      - name: Run test
        run : make test